<?php
/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace HealthOSLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class AllExercisesResponse18 implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var string $name public property
     */
    public $name;

    /**
     * @todo Write general description for this property
     * @required
     * @maps calory_count
     * @var string $caloryCount public property
     */
    public $caloryCount;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $category public property
     */
    public $category;

    /**
     * @todo Write general description for this property
     * @required
     * @maps cardio_subcategory
     * @var string $cardioSubcategory public property
     */
    public $cardioSubcategory;

    /**
     * @todo Write general description for this property
     * @required
     * @maps primary_muscle_group
     * @var string $primaryMuscleGroup public property
     */
    public $primaryMuscleGroup;

    /**
     * @todo Write general description for this property
     * @required
     * @maps exercise_id
     * @var string $exerciseId public property
     */
    public $exerciseId;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $name               Initialization value for $this->name
     * @param string $caloryCount        Initialization value for $this->caloryCount
     * @param string $category           Initialization value for $this->category
     * @param string $cardioSubcategory  Initialization value for $this->cardioSubcategory
     * @param string $primaryMuscleGroup Initialization value for $this->primaryMuscleGroup
     * @param string $exerciseId         Initialization value for $this->exerciseId
     */
    public function __construct()
    {
        if (6 == func_num_args()) {
            $this->name               = func_get_arg(0);
            $this->caloryCount        = func_get_arg(1);
            $this->category           = func_get_arg(2);
            $this->cardioSubcategory  = func_get_arg(3);
            $this->primaryMuscleGroup = func_get_arg(4);
            $this->exerciseId         = func_get_arg(5);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['name']                 = $this->name;
        $json['calory_count']         = $this->caloryCount;
        $json['category']             = $this->category;
        $json['cardio_subcategory']   = $this->cardioSubcategory;
        $json['primary_muscle_group'] = $this->primaryMuscleGroup;
        $json['exercise_id']          = $this->exerciseId;

        return $json;
    }
}
