<?php
/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace HealthOSLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class AllFoodRestaurantsResponse implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @maps restaurant_name
     * @var string $restaurantName public property
     */
    public $restaurantName;

    /**
     * @todo Write general description for this property
     * @required
     * @maps food_restaurant_id
     * @var string $foodRestaurantId public property
     */
    public $foodRestaurantId;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $restaurantName   Initialization value for $this->restaurantName
     * @param string $foodRestaurantId Initialization value for $this->foodRestaurantId
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->restaurantName   = func_get_arg(0);
            $this->foodRestaurantId = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['restaurant_name']    = $this->restaurantName;
        $json['food_restaurant_id'] = $this->foodRestaurantId;

        return $json;
    }
}
