<?php
/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace HealthOSLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class AllFoodBrandsResponse implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @maps brand_name
     * @var string $brandName public property
     */
    public $brandName;

    /**
     * @todo Write general description for this property
     * @required
     * @maps food_brand_id
     * @var string $foodBrandId public property
     */
    public $foodBrandId;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $brandName   Initialization value for $this->brandName
     * @param string $foodBrandId Initialization value for $this->foodBrandId
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->brandName   = func_get_arg(0);
            $this->foodBrandId = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['brand_name']    = $this->brandName;
        $json['food_brand_id'] = $this->foodBrandId;

        return $json;
    }
}
