<?php
/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace HealthOSLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class AllGenericsResponse implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var string $name public property
     */
    public $name;

    /**
     * @todo Write general description for this property
     * @required
     * @maps pregnancy_category
     * @var string $pregnancyCategory public property
     */
    public $pregnancyCategory;

    /**
     * @todo Write general description for this property
     * @required
     * @maps lactation_category
     * @var string $lactationCategory public property
     */
    public $lactationCategory;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $instructions public property
     */
    public $instructions;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $faqs public property
     */
    public $faqs;

    /**
     * @todo Write general description for this property
     * @required
     * @maps genric_id
     * @var integer $genricId public property
     */
    public $genricId;

    /**
     * @todo Write general description for this property
     * @required
     * @maps side_effects
     * @var string $sideEffects public property
     */
    public $sideEffects;

    /**
     * @todo Write general description for this property
     * @required
     * @maps how_it_works
     * @var string $howItWorks public property
     */
    public $howItWorks;

    /**
     * @todo Write general description for this property
     * @required
     * @maps therapeutic_class
     * @var string $therapeuticClass public property
     */
    public $therapeuticClass;

    /**
     * @todo Write general description for this property
     * @required
     * @maps used_for
     * @var string $usedFor public property
     */
    public $usedFor;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $strength public property
     */
    public $strength;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $schedule public property
     */
    public $schedule;

    /**
     * @todo Write general description for this property
     * @required
     * @maps alcohol_interaction_description
     * @var string $alcoholInteractionDescription public property
     */
    public $alcoholInteractionDescription;

    /**
     * @todo Write general description for this property
     * @required
     * @maps alcohol_nteraction
     * @var bool $alcoholNteraction public property
     */
    public $alcoholNteraction;

    /**
     * Constructor to set initial or default values of member properties
     * @param string  $name                          Initialization value for $this->name
     * @param string  $pregnancyCategory             Initialization value for $this->pregnancyCategory
     * @param string  $lactationCategory             Initialization value for $this->lactationCategory
     * @param string  $instructions                  Initialization value for $this->instructions
     * @param string  $faqs                          Initialization value for $this->faqs
     * @param integer $genricId                      Initialization value for $this->genricId
     * @param string  $sideEffects                   Initialization value for $this->sideEffects
     * @param string  $howItWorks                    Initialization value for $this->howItWorks
     * @param string  $therapeuticClass              Initialization value for $this->therapeuticClass
     * @param string  $usedFor                       Initialization value for $this->usedFor
     * @param string  $strength                      Initialization value for $this->strength
     * @param string  $schedule                      Initialization value for $this->schedule
     * @param string  $alcoholInteractionDescription Initialization value for $this->alcoholInteractionDescription
     * @param bool    $alcoholNteraction             Initialization value for $this->alcoholNteraction
     */
    public function __construct()
    {
        if (14 == func_num_args()) {
            $this->name                          = func_get_arg(0);
            $this->pregnancyCategory             = func_get_arg(1);
            $this->lactationCategory             = func_get_arg(2);
            $this->instructions                  = func_get_arg(3);
            $this->faqs                          = func_get_arg(4);
            $this->genricId                      = func_get_arg(5);
            $this->sideEffects                   = func_get_arg(6);
            $this->howItWorks                    = func_get_arg(7);
            $this->therapeuticClass              = func_get_arg(8);
            $this->usedFor                       = func_get_arg(9);
            $this->strength                      = func_get_arg(10);
            $this->schedule                      = func_get_arg(11);
            $this->alcoholInteractionDescription = func_get_arg(12);
            $this->alcoholNteraction             = func_get_arg(13);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['name']                            = $this->name;
        $json['pregnancy_category']              = $this->pregnancyCategory;
        $json['lactation_category']              = $this->lactationCategory;
        $json['instructions']                    = $this->instructions;
        $json['faqs']                            = $this->faqs;
        $json['genric_id']                       = $this->genricId;
        $json['side_effects']                    = $this->sideEffects;
        $json['how_it_works']                    = $this->howItWorks;
        $json['therapeutic_class']               = $this->therapeuticClass;
        $json['used_for']                        = $this->usedFor;
        $json['strength']                        = $this->strength;
        $json['schedule']                        = $this->schedule;
        $json['alcohol_interaction_description'] = $this->alcoholInteractionDescription;
        $json['alcohol_nteraction']              = $this->alcoholNteraction;

        return $json;
    }
}
