<?php
/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace HealthOSLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class AllLabTestsResponse implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @maps lab_test_name
     * @var string $labTestName public property
     */
    public $labTestName;

    /**
     * @todo Write general description for this property
     * @required
     * @maps alternate_name
     * @var string $alternateName public property
     */
    public $alternateName;

    /**
     * @todo Write general description for this property
     * @required
     * @maps lab_test_id
     * @var string $labTestId public property
     */
    public $labTestId;

    /**
     * @todo Write general description for this property
     * @required
     * @maps lab_test_data
     * @var LabTestData34 $labTestData public property
     */
    public $labTestData;

    /**
     * Constructor to set initial or default values of member properties
     * @param string        $labTestName   Initialization value for $this->labTestName
     * @param string        $alternateName Initialization value for $this->alternateName
     * @param string        $labTestId     Initialization value for $this->labTestId
     * @param LabTestData34 $labTestData   Initialization value for $this->labTestData
     */
    public function __construct()
    {
        if (4 == func_num_args()) {
            $this->labTestName   = func_get_arg(0);
            $this->alternateName = func_get_arg(1);
            $this->labTestId     = func_get_arg(2);
            $this->labTestData   = func_get_arg(3);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['lab_test_name']  = $this->labTestName;
        $json['alternate_name'] = $this->alternateName;
        $json['lab_test_id']    = $this->labTestId;
        $json['lab_test_data']  = $this->labTestData;

        return $json;
    }
}
