<?php
/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace HealthOSLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class CommonSideEffectsResponse implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var string $generic public property
     */
    public $generic;

    /**
     * @todo Write general description for this property
     * @required
     * @maps side_effects
     * @var SideEffect[] $sideEffects public property
     */
    public $sideEffects;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $generic     Initialization value for $this->generic
     * @param array  $sideEffects Initialization value for $this->sideEffects
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->generic     = func_get_arg(0);
            $this->sideEffects = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['generic']      = $this->generic;
        $json['side_effects'] = $this->sideEffects;

        return $json;
    }
}
