<?php
/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace HealthOSLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Constituent implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var string $name public property
     */
    public $name;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $strength public property
     */
    public $strength;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $name     Initialization value for $this->name
     * @param string $strength Initialization value for $this->strength
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->name     = func_get_arg(0);
            $this->strength = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['name']     = $this->name;
        $json['strength'] = $this->strength;

        return $json;
    }
}
