<?php
/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace HealthOSLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class GenericsResponse implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var string $name public property
     */
    public $name;

    /**
     * @todo Write general description for this property
     * @required
     * @maps generic_id
     * @var string $genericId public property
     */
    public $genericId;

    /**
     * @todo Write general description for this property
     * @required
     * @maps therauptic_uses
     * @var array $theraupticUses public property
     */
    public $theraupticUses;

    /**
     * @todo Write general description for this property
     * @required
     * @maps search_score
     * @var double $searchScore public property
     */
    public $searchScore;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $name           Initialization value for $this->name
     * @param string $genericId      Initialization value for $this->genericId
     * @param array  $theraupticUses Initialization value for $this->theraupticUses
     * @param double $searchScore    Initialization value for $this->searchScore
     */
    public function __construct()
    {
        if (4 == func_num_args()) {
            $this->name           = func_get_arg(0);
            $this->genericId      = func_get_arg(1);
            $this->theraupticUses = func_get_arg(2);
            $this->searchScore    = func_get_arg(3);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['name']            = $this->name;
        $json['generic_id']      = $this->genericId;
        $json['therauptic_uses'] = $this->theraupticUses;
        $json['search_score']    = $this->searchScore;

        return $json;
    }
}
