<?php
/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace HealthOSLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Interaction implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var Item[] $items public property
     */
    public $items;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $severity public property
     */
    public $severity;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $description public property
     */
    public $description;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $source public property
     */
    public $source;

    /**
     * Constructor to set initial or default values of member properties
     * @param array  $items       Initialization value for $this->items
     * @param string $severity    Initialization value for $this->severity
     * @param string $description Initialization value for $this->description
     * @param string $source      Initialization value for $this->source
     */
    public function __construct()
    {
        if (4 == func_num_args()) {
            $this->items       = func_get_arg(0);
            $this->severity    = func_get_arg(1);
            $this->description = func_get_arg(2);
            $this->source      = func_get_arg(3);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['items']       = $this->items;
        $json['severity']    = $this->severity;
        $json['description'] = $this->description;
        $json['source']      = $this->source;

        return $json;
    }
}
