<?php
/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace HealthOSLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class LabTestData34 implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @maps Ordering information
     * @var string $orderingInformation public property
     */
    public $orderingInformation;

    /**
     * @todo Write general description for this property
     * @required
     * @maps Laboratory
     * @var string $laboratory public property
     */
    public $laboratory;

    /**
     * @todo Write general description for this property
     * @required
     * @maps Test Code
     * @var string $testCode public property
     */
    public $testCode;

    /**
     * @todo Write general description for this property
     * @required
     * @maps Specimen types
     * @var string $specimenTypes public property
     */
    public $specimenTypes;

    /**
     * @todo Write general description for this property
     * @required
     * @maps Container types
     * @var string $containerTypes public property
     */
    public $containerTypes;

    /**
     * @todo Write general description for this property
     * @required
     * @maps Collection Instructions
     * @var string $collectionInstructions public property
     */
    public $collectionInstructions;

    /**
     * @todo Write general description for this property
     * @required
     * @maps Frequency
     * @var string $frequency public property
     */
    public $frequency;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $orderingInformation    Initialization value for $this->orderingInformation
     * @param string $laboratory             Initialization value for $this->laboratory
     * @param string $testCode               Initialization value for $this->testCode
     * @param string $specimenTypes          Initialization value for $this->specimenTypes
     * @param string $containerTypes         Initialization value for $this->containerTypes
     * @param string $collectionInstructions Initialization value for $this->collectionInstructions
     * @param string $frequency              Initialization value for $this->frequency
     */
    public function __construct()
    {
        if (7 == func_num_args()) {
            $this->orderingInformation    = func_get_arg(0);
            $this->laboratory             = func_get_arg(1);
            $this->testCode               = func_get_arg(2);
            $this->specimenTypes          = func_get_arg(3);
            $this->containerTypes         = func_get_arg(4);
            $this->collectionInstructions = func_get_arg(5);
            $this->frequency              = func_get_arg(6);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['Ordering information']    = $this->orderingInformation;
        $json['Laboratory']              = $this->laboratory;
        $json['Test Code']               = $this->testCode;
        $json['Specimen types']          = $this->specimenTypes;
        $json['Container types']         = $this->containerTypes;
        $json['Collection Instructions'] = $this->collectionInstructions;
        $json['Frequency']               = $this->frequency;

        return $json;
    }
}
