<?php
/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace HealthOSLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class LabTestsResponse implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @maps alternate_name
     * @var string $alternateName public property
     */
    public $alternateName;

    /**
     * @todo Write general description for this property
     * @required
     * @maps lab_test_data
     * @var LabTestData $labTestData public property
     */
    public $labTestData;

    /**
     * @todo Write general description for this property
     * @required
     * @maps lab_test_id
     * @var string $labTestId public property
     */
    public $labTestId;

    /**
     * @todo Write general description for this property
     * @required
     * @maps lab_test_name
     * @var string $labTestName public property
     */
    public $labTestName;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $id public property
     */
    public $id;

    /**
     * @todo Write general description for this property
     * @required
     * @maps search_score
     * @var double $searchScore public property
     */
    public $searchScore;

    /**
     * Constructor to set initial or default values of member properties
     * @param string      $alternateName Initialization value for $this->alternateName
     * @param LabTestData $labTestData   Initialization value for $this->labTestData
     * @param string      $labTestId     Initialization value for $this->labTestId
     * @param string      $labTestName   Initialization value for $this->labTestName
     * @param string      $id            Initialization value for $this->id
     * @param double      $searchScore   Initialization value for $this->searchScore
     */
    public function __construct()
    {
        if (6 == func_num_args()) {
            $this->alternateName = func_get_arg(0);
            $this->labTestData   = func_get_arg(1);
            $this->labTestId     = func_get_arg(2);
            $this->labTestName   = func_get_arg(3);
            $this->id            = func_get_arg(4);
            $this->searchScore   = func_get_arg(5);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['alternate_name'] = $this->alternateName;
        $json['lab_test_data']  = $this->labTestData;
        $json['lab_test_id']    = $this->labTestId;
        $json['lab_test_name']  = $this->labTestName;
        $json['id']             = $this->id;
        $json['search_score']   = $this->searchScore;

        return $json;
    }
}
