<?php
/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace HealthOSLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class LabTestData implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @maps Ordering information
     * @var string $orderingInformation public property
     */
    public $orderingInformation;

    /**
     * @todo Write general description for this property
     * @required
     * @maps Alternate names
     * @var string $alternateNames public property
     */
    public $alternateNames;

    /**
     * @todo Write general description for this property
     * @required
     * @maps Laboratory
     * @var string $laboratory public property
     */
    public $laboratory;

    /**
     * @todo Write general description for this property
     * @required
     * @maps Test Code
     * @var string $testCode public property
     */
    public $testCode;

    /**
     * @todo Write general description for this property
     * @required
     * @maps Specimen types
     * @var string $specimenTypes public property
     */
    public $specimenTypes;

    /**
     * @todo Write general description for this property
     * @required
     * @maps Container types
     * @var string $containerTypes public property
     */
    public $containerTypes;

    /**
     * @todo Write general description for this property
     * @required
     * @maps Minimum Adult Volume
     * @var string $minimumAdultVolume public property
     */
    public $minimumAdultVolume;

    /**
     * @todo Write general description for this property
     * @required
     * @maps Frequency
     * @var string $frequency public property
     */
    public $frequency;

    /**
     * @todo Write general description for this property
     * @required
     * @maps External Laboratory
     * @var string $externalLaboratory public property
     */
    public $externalLaboratory;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $orderingInformation Initialization value for $this->orderingInformation
     * @param string $alternateNames      Initialization value for $this->alternateNames
     * @param string $laboratory          Initialization value for $this->laboratory
     * @param string $testCode            Initialization value for $this->testCode
     * @param string $specimenTypes       Initialization value for $this->specimenTypes
     * @param string $containerTypes      Initialization value for $this->containerTypes
     * @param string $minimumAdultVolume  Initialization value for $this->minimumAdultVolume
     * @param string $frequency           Initialization value for $this->frequency
     * @param string $externalLaboratory  Initialization value for $this->externalLaboratory
     */
    public function __construct()
    {
        if (9 == func_num_args()) {
            $this->orderingInformation = func_get_arg(0);
            $this->alternateNames      = func_get_arg(1);
            $this->laboratory          = func_get_arg(2);
            $this->testCode            = func_get_arg(3);
            $this->specimenTypes       = func_get_arg(4);
            $this->containerTypes      = func_get_arg(5);
            $this->minimumAdultVolume  = func_get_arg(6);
            $this->frequency           = func_get_arg(7);
            $this->externalLaboratory  = func_get_arg(8);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['Ordering information'] = $this->orderingInformation;
        $json['Alternate names']      = $this->alternateNames;
        $json['Laboratory']           = $this->laboratory;
        $json['Test Code']            = $this->testCode;
        $json['Specimen types']       = $this->specimenTypes;
        $json['Container types']      = $this->containerTypes;
        $json['Minimum Adult Volume'] = $this->minimumAdultVolume;
        $json['Frequency']            = $this->frequency;
        $json['External Laboratory']  = $this->externalLaboratory;

        return $json;
    }
}
