<?php
/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace HealthOSLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class MedicinesByManufacturerResponse implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var string $name public property
     */
    public $name;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $form public property
     */
    public $form;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $standardUnits public property
     */
    public $standardUnits;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $packageForm public property
     */
    public $packageForm;

    /**
     * @todo Write general description for this property
     * @required
     * @var double $price public property
     */
    public $price;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $size public property
     */
    public $size;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $manufacturer public property
     */
    public $manufacturer;

    /**
     * @todo Write general description for this property
     * @required
     * @var Constituent[] $constituents public property
     */
    public $constituents;

    /**
     * @todo Write general description for this property
     * @required
     * @var Schedule $schedule public property
     */
    public $schedule;

    /**
     * @todo Write general description for this property
     * @required
     * @maps medicine_id
     * @var string $medicineId public property
     */
    public $medicineId;

    /**
     * Constructor to set initial or default values of member properties
     * @param string   $name          Initialization value for $this->name
     * @param string   $form          Initialization value for $this->form
     * @param integer  $standardUnits Initialization value for $this->standardUnits
     * @param string   $packageForm   Initialization value for $this->packageForm
     * @param double   $price         Initialization value for $this->price
     * @param string   $size          Initialization value for $this->size
     * @param string   $manufacturer  Initialization value for $this->manufacturer
     * @param array    $constituents  Initialization value for $this->constituents
     * @param Schedule $schedule      Initialization value for $this->schedule
     * @param string   $medicineId    Initialization value for $this->medicineId
     */
    public function __construct()
    {
        if (10 == func_num_args()) {
            $this->name          = func_get_arg(0);
            $this->form          = func_get_arg(1);
            $this->standardUnits = func_get_arg(2);
            $this->packageForm   = func_get_arg(3);
            $this->price         = func_get_arg(4);
            $this->size          = func_get_arg(5);
            $this->manufacturer  = func_get_arg(6);
            $this->constituents  = func_get_arg(7);
            $this->schedule      = func_get_arg(8);
            $this->medicineId    = func_get_arg(9);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['name']          = $this->name;
        $json['form']          = $this->form;
        $json['standardUnits'] = $this->standardUnits;
        $json['packageForm']   = $this->packageForm;
        $json['price']         = $this->price;
        $json['size']          = $this->size;
        $json['manufacturer']  = $this->manufacturer;
        $json['constituents']  = $this->constituents;
        $json['schedule']      = $this->schedule;
        $json['medicine_id']   = $this->medicineId;

        return $json;
    }
}
