<?php
/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace HealthOSLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class PopularUsageResponse implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var string $generic public property
     */
    public $generic;

    /**
     * @todo Write general description for this property
     * @required
     * @var Usage[] $usages public property
     */
    public $usages;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $generic Initialization value for $this->generic
     * @param array  $usages  Initialization value for $this->usages
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->generic = func_get_arg(0);
            $this->usages  = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['generic'] = $this->generic;
        $json['usages']  = $this->usages;

        return $json;
    }
}
