<?php
/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace HealthOSLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class RequestAccessTokenRequest implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @maps grant_type
     * @var string $grantType public property
     */
    public $grantType;

    /**
     * @todo Write general description for this property
     * @required
     * @maps client_id
     * @var string $clientId public property
     */
    public $clientId;

    /**
     * @todo Write general description for this property
     * @required
     * @maps client_secret
     * @var string $clientSecret public property
     */
    public $clientSecret;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $scope public property
     */
    public $scope;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $grantType    Initialization value for $this->grantType
     * @param string $clientId     Initialization value for $this->clientId
     * @param string $clientSecret Initialization value for $this->clientSecret
     * @param string $scope        Initialization value for $this->scope
     */
    public function __construct()
    {
        if (4 == func_num_args()) {
            $this->grantType    = func_get_arg(0);
            $this->clientId     = func_get_arg(1);
            $this->clientSecret = func_get_arg(2);
            $this->scope        = func_get_arg(3);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['grant_type']    = $this->grantType;
        $json['client_id']     = $this->clientId;
        $json['client_secret'] = $this->clientSecret;
        $json['scope']         = $this->scope;

        return $json;
    }
}
