<?php
/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace HealthOSLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Schedule implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var string $category public property
     */
    public $category;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $label public property
     */
    public $label;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $category Initialization value for $this->category
     * @param string $label    Initialization value for $this->label
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->category = func_get_arg(0);
            $this->label    = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['category'] = $this->category;
        $json['label']    = $this->label;

        return $json;
    }
}
