<?php
/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace HealthOSLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class SearchFoodItemsResponse implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var integer $calories public property
     */
    public $calories;

    /**
     * @todo Write general description for this property
     * @required
     * @maps item_name
     * @var string $itemName public property
     */
    public $itemName;

    /**
     * @todo Write general description for this property
     * @required
     * @maps serving_qty
     * @var double $servingQty public property
     */
    public $servingQty;

    /**
     * @todo Write general description for this property
     * @required
     * @maps serving_unit
     * @var string $servingUnit public property
     */
    public $servingUnit;

    /**
     * @todo Write general description for this property
     * @required
     * @maps food_brand_id
     * @var string $foodBrandId public property
     */
    public $foodBrandId;

    /**
     * @todo Write general description for this property
     * @required
     * @maps food_item_id
     * @var string $foodItemId public property
     */
    public $foodItemId;

    /**
     * @todo Write general description for this property
     * @required
     * @maps search_score
     * @var double $searchScore public property
     */
    public $searchScore;

    /**
     * Constructor to set initial or default values of member properties
     * @param integer $calories    Initialization value for $this->calories
     * @param string  $itemName    Initialization value for $this->itemName
     * @param double  $servingQty  Initialization value for $this->servingQty
     * @param string  $servingUnit Initialization value for $this->servingUnit
     * @param string  $foodBrandId Initialization value for $this->foodBrandId
     * @param string  $foodItemId  Initialization value for $this->foodItemId
     * @param double  $searchScore Initialization value for $this->searchScore
     */
    public function __construct()
    {
        if (7 == func_num_args()) {
            $this->calories    = func_get_arg(0);
            $this->itemName    = func_get_arg(1);
            $this->servingQty  = func_get_arg(2);
            $this->servingUnit = func_get_arg(3);
            $this->foodBrandId = func_get_arg(4);
            $this->foodItemId  = func_get_arg(5);
            $this->searchScore = func_get_arg(6);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['calories']      = $this->calories;
        $json['item_name']     = $this->itemName;
        $json['serving_qty']   = $this->servingQty;
        $json['serving_unit']  = $this->servingUnit;
        $json['food_brand_id'] = $this->foodBrandId;
        $json['food_item_id']  = $this->foodItemId;
        $json['search_score']  = $this->searchScore;

        return $json;
    }
}
