<?php
/*
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace HealthOSLib;

use HealthOSLib\Controllers;

/**
 * HealthOSLib client class
 */
class HealthOSClient
{
    /**
     * Constructor with authentication and configuration parameters
     */
    public function __construct(
        $host = null,
        $oAuthAccessToken = null
    ) {
        Configuration::$host = $host ? $host : Configuration::$host;
        Configuration::$oAuthAccessToken = $oAuthAccessToken ? $oAuthAccessToken : Configuration::$oAuthAccessToken;
    }
 
    /**
     * Singleton access to Medicines controller
     * @return Controllers\MedicinesController The *Singleton* instance
     */
    public function getMedicines()
    {
        return Controllers\MedicinesController::getInstance();
    }
 
    /**
     * Singleton access to LabTests controller
     * @return Controllers\LabTestsController The *Singleton* instance
     */
    public function getLabTests()
    {
        return Controllers\LabTestsController::getInstance();
    }
 
    /**
     * Singleton access to Generics controller
     * @return Controllers\GenericsController The *Singleton* instance
     */
    public function getGenerics()
    {
        return Controllers\GenericsController::getInstance();
    }
 
    /**
     * Singleton access to Food controller
     * @return Controllers\FoodController The *Singleton* instance
     */
    public function getFood()
    {
        return Controllers\FoodController::getInstance();
    }
 
    /**
     * Singleton access to Exercises controller
     * @return Controllers\ExercisesController The *Singleton* instance
     */
    public function getExercises()
    {
        return Controllers\ExercisesController::getInstance();
    }
 
    /**
     * Singleton access to DrugInteractions controller
     * @return Controllers\DrugInteractionsController The *Singleton* instance
     */
    public function getDrugInteractions()
    {
        return Controllers\DrugInteractionsController::getInstance();
    }
 
    /**
     * Singleton access to Diseases controller
     * @return Controllers\DiseasesController The *Singleton* instance
     */
    public function getDiseases()
    {
        return Controllers\DiseasesController::getInstance();
    }
 
    /**
     * Singleton access to Chat controller
     * @return Controllers\ChatController The *Singleton* instance
     */
    public function getChat()
    {
        return Controllers\ChatController::getInstance();
    }
 
    /**
     * Singleton access to Autocomplete controller
     * @return Controllers\AutocompleteController The *Singleton* instance
     */
    public function getAutocomplete()
    {
        return Controllers\AutocompleteController::getInstance();
    }
 
    /**
     * Singleton access to Authentication controller
     * @return Controllers\AuthenticationController The *Singleton* instance
     */
    public function getAuthentication()
    {
        return Controllers\AuthenticationController::getInstance();
    }
}
